### PR TITLE
Utils to show modulename with its repr(); Add Linear weighted activations as objective; Add pretrained GAN as parametrization

### PR DESCRIPTION
**Pull request by Animadversio**
Dear author, 

Thanks so much for implement lucid in PyTorch! I really enjoyed using it in my projects of leveraging deep neural networks as a way to understand real neurons in visual cortices. In my usage, I want to activate multiple channels together to match the selectivity of the biological neuron or units in other networks. We can achieve this by adding up the original channel objective or neuron objective. But it becomes very inefficient in back prop. 

So here are my 2 cents, in this commit I 
- Add linearly weighted activations of the channel, neuron, neuron group as objective. Using tensor operations. 
- Add a function in util.py to output the module names to ease the usage for custom networks.

### CODE REVIEW

**Comment by greentfrapp** [comment]
@Animadversio thanks for the contribution! And I'm glad Lucent helped with your work.

The linearly weighted activations parts look good. Can you add some tests in `tests/optvis/test_objectives.py` for the new objective functions? You can run the tests with
```
$ coverage run --source . --omit setup.py -m pytest
$ coverage report -m
```

Regarding the new `lucent_layernames` function in `util.py`, it's actually already there, under `get_model_layers` in `lucent/modelzoo/util.py` https://github.com/greentfrapp/lucent/blob/044317a7b395220e6a27fd890c35abc081c5d1c8/lucent/modelzoo/util.py#L21
Although I just realized that I didn't add the following snippet! 
```
if layer is None:
    # e.g. GoogLeNet's aux1 and aux2 layers
    continue
```

Can you make this change in the `modelzoo/util.py` file instead? Thanks!!!

**Comment by Animadversio** [comment]
Sure! Thanks for telling me how to run tests!  Haven't tried that before

**Comment by Animadversio** [comment]
@greentfrapp Hi! I add tests for the new objectives and besides I add a new kind of parametrization. Use pretrained GAN as prior to visualize feature. I have added tests for these new functionalities! 

The code is inspired by 
Nguyen, A., Dosovitskiy, A., Yosinski, J., Brox, T., & Clune, J.
    Synthesizing the preferred inputs for neurons in neural networks via deep generator networks.(2016) NIPS
I have translated it into pytorch and host the weights of the pretrained GAN in my personal space.

**Comment by greentfrapp** [comment]
Thanks @Animadversio! The GAN-as-prior work looks interesting and intuitively will work better for higher-level layers compared to lower-level ones, due to the way the GAN is trained. I will be merging this for now, but I think it'll be helpful if you could also add a notebook to demonstrate the use of the GAN prior!

**Pull request merged**
